# Generated by Django 3.0.5 on 2020-04-26 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('population', models.IntegerField(default=0)),
                ('cities_count', models.IntegerField(default=0)),
                ('flag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locations.Symbol')),
            ],
        ),
    ]
