# Generated by Django 3.0.5 on 2020-04-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_country_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cities_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
