# Generated by Django 3.0.5 on 2020-04-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_city_cities_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='cities_count',
        ),
    ]
