# Generated by Django 3.0.5 on 2020-05-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_remove_city_cities_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
